# Generated by Django 5.1.1 on 2024-10-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='duration',
        ),
    ]
