# Generated by Django 5.1.1 on 2024-11-13 14:19

import apps.tasks.models
import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending Upload"),
                    ("Uploaded", "Uploaded"),
                    ("Failed", "Failed"),
                ],
                default="Pending Upload",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                storage=django_minio_backend.models.MinioBackend(bucket_name="media"),
                upload_to=apps.tasks.models.Attachment.custom_file_name,
            ),
        ),
    ]
