# Generated by Django 5.1.1 on 2024-11-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0011_attachment_status_alter_attachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
