# Generated by Django 5.1.1 on 2024-11-18 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_attachment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
