# Generated by Django 5.1.1 on 2024-11-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0013_attachment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
