services:
  db:
    image: postgres:14
    container_name: postgres
    command: -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    env_file:
      - .env

  pghero:
    image: ankane/pghero
    container_name: pghero
    ports:
      - "8080:8080"
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env


volumes:
  postgres_data:
    driver: local
