name: Django Test with Ruff Linting

on:
  push:
    branches:
      - main
      - '**'

  pull_request:
    branches:
      - main
      - '**'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}" >> .env
          echo "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "MINIO_STORAGE_HOST=${{ secrets.MINIO_STORAGE_HOST }}" >> .env
          echo "MAILHOG_HOST=${{ secrets.MAILHOG_HOST }}" >> .env
          echo "ELASTIC_HOST=${{ secrets.ELASTIC_HOST }}" >> .env
          echo "ELASTICSEARCH_PASSWORD=${{ secrets.ELASTICSEARCH_PASSWORD }}" >> .env
          echo "ELASTICSEARCH_USERNAME=${{ secrets.ELASTICSEARCH_USERNAME }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
          echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> .env

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipx
          python -m pipx ensurepath
          export PATH="$HOME/.local/bin:$PATH"
          pipx install poetry
          poetry install

      - name: Run Ruff Linter
        run: |
            poetry run ruff check .

      - name: Build Docker image
        run: docker build -t ebs-task-management-system-api .

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          services: |
            db
            redis
            minio
            mailhog
            celery
            celery-beat
            elasticsearch

      - name: Wait for Elasticsearch
        run: |
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:9200)" != "200" ]]; do sleep 5; done' || false

      - name: Run tests with coverage
        run: |
          poetry run coverage run manage.py test

      - name: Display coverage report
        run: |
          poetry run coverage report

      - name: Generate coverage reports
        run: |
          poetry run coverage xml
          poetry run coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: htmlcov/